In [1]:
import numpy as np
import pandas as pd
from init import *

In [2]:
# a numpy array with missing entry to fit GLRM onto
A = np.array([[1, 2, np.nan, 4], [2, 4, 6, 8], [4, 5, 6, 7]])

In [3]:
# a list of regularizers for each column
ry = [ZeroReg(), NonNegConstraint(), ZeroReg(), ZeroReg()]

In [4]:
# generalized PCA and projection
g = glrm(n_components=2, ry=ry) 
g.set_training_data(inputs=A)
g.fit()
a_new = np.array([6, 7, 8, 9]) 
x = g.transform(inputs=a_new) 

In [5]:
A

array([[ 1.,  2., nan,  4.],
       [ 2.,  4.,  6.,  8.],
       [ 4.,  5.,  6.,  7.]])

In [6]:
g.X

array([[1.81735469, 3.6254816 , 4.77715843],
       [2.13729697, 4.26736634, 2.83797073]])

In [7]:
g.X

array([[1.81735469, 3.6254816 , 4.77715843],
       [2.13729697, 4.26736634, 2.83797073]])

In [8]:
g.Y

array([[ 1.14072176,  0.97384024,  0.8408922 ,  0.72104433],
       [-0.50274876,  0.1117748 ,  0.69353317,  1.25946316]])

In [9]:
x

array([[6.75334943],
       [3.3091475 ]])

In [10]:
# PCA 
h = glrm(n_components=2, offset=True, scale=True)

In [11]:
h.fit_transform(pd.DataFrame(A))

0    1
0  0.369732  1.0
1 -0.336232  1.0
2 -0.480326  1.0

In [12]:
h.fit_transform(A)

array([[0.64108169, 1.        ],
       [1.55840099, 1.        ],
       [1.72881939, 1.        ]])

In [13]:
B = np.array([[1, 2, np.nan, 4], [2, 4, np.nan, 8], [4, 5, np.nan, 7]])
h2 = glrm(n_components=3)
h2.fit_transform(B)

array([[ 1.09574895,  0.12242331, -1.94457538],
       [ 2.08578364,  0.44514506, -3.85969746],
       [-1.31633739, -0.13385953, -4.75295771]])

In [14]:
#Python automatically converts integers to floats, thus I have not implemented the functionality of initializing losses and regularizers by types
a = np.array([[1, 2], [3.2, 4.2]])