In [1]:
import numpy as np
import pandas as pd
from pyglrm import *

In [2]:
# a numpy array with missing entry to fit GLRM onto
A = np.array([[1, 2, np.nan, 4], [2, 4, 6, 8], [4, 5, 6, 7]])

In [4]:
# a list of regularizers for each column
ry = [ZeroReg(), NonNegConstraint(), ZeroReg(), ZeroReg()]

In [4]:
# generalized PCA and projection
g = glrm(n_components=2, ry=ry) 
g.set_training_data(inputs=A)
g.fit()
a_new = np.array([6, 7, 8, 9]) 
x = g.transform(inputs=a_new) 

In [5]:
x

array([[ 3.65388666],
       [-0.43974294]])

In [20]:
hp = glrm(rx=NonNegConstraint(), ry=NonNegConstraint())
hp.set_training_data(inputs=A)
hp.fit()
a_new = np.array([6, 7, 8, 9]) 
x = hp.transform(inputs=a_new) 

In [21]:
hp.get_hyperprams()

{'losses': <PyCall.jlwrap LowRankModels.QuadLoss(1.0, LowRankModels.RealDomain())>,
 'rx': <PyCall.jlwrap LowRankModels.NonNegConstraint()>,
 'ry': <PyCall.jlwrap LowRankModels.NonNegConstraint()>,
 'n_components': 2,
 'obs': [(0, 0),
  (0, 1),
  (0, 2),
  (0, 3),
  (1, 0),
  (1, 1),
  (1, 2),
  (1, 3),
  (2, 0),
  (2, 1),
  (2, 2),
  (2, 3)],
 'offset': False,
 'scale': False}

In [3]:
h = nnmf(n_components=5)

In [4]:
h.get_hyperprams()

{'losses': <PyCall.jlwrap LowRankModels.QuadLoss(1.0, LowRankModels.RealDomain())>,
 'rx': <PyCall.jlwrap LowRankModels.NonNegConstraint()>,
 'ry': <PyCall.jlwrap LowRankModels.NonNegConstraint()>,
 'n_components': 5,
 'obs': None,
 'offset': False,
 'scale': False}

In [26]:
h.set_training_data(inputs=A)
h.fit()
a_new = np.array([6, 7, 8, 9]) 
x = h.transform(inputs=a_new) 

RuntimeError: Julia exception: MethodError(Type, (Any[:obs, Tuple{Int64,Int64}[(1, 1), (1, 2), (1, 3), (1, 4), (2, 1), (2, 2), (2, 3), (2, 4), (3, 1), (3, 2), (3, 3), (3, 4)], :offset, false, :scale, false], LowRankModels.GLRM, [1 2 3 4; 2 4 6 8; 4 5 6 7], LowRankModels.QuadLoss(1.0, LowRankModels.RealDomain()), LowRankModels.NonNegConstraint(), LowRankModels.NonNegConstraint(), false), 0x0000000000005569)

In [6]:
# PCA 
h = glrm(n_components=2, offset=True, scale=True)

In [7]:
h.fit_impute(pd.DataFrame(A))

0         1         2         3
0  0.854339  1.991302  4.355311  4.264312
1  2.796350  4.190537  5.777283  6.974481
2  3.363850  4.833203  6.192816  7.766454

In [11]:
h.fit_transform(A)

array([[0.41333745, 1.        ],
       [1.16132327, 1.        ],
       [1.3819136 , 1.        ]])

In [9]:
B = np.array([[1, 2, np.nan, 4], [2, 4, np.nan, 8], [4, 5, np.nan, 7]])
h2 = glrm(n_components=3)
h2.fit_transform(B)

array([[-1.06595238, -0.82868562, -0.32365888],
       [-2.12920767, -1.64910571, -0.65757441],
       [-1.81494602, -0.57559055, -2.28062293]])

In [10]:
#Python automatically converts integers to floats, thus I have not implemented the functionality of initializing losses and regularizers by types
a = np.array([[1, 2], [3.2, 4.2]])