In [1]:
import numpy as np
import pandas as pd
from init import *

In [2]:
# a numpy array with missing entry to fit GLRM onto
A = np.array([[1, 2, np.nan, 4], [2, 4, 6, 8], [4, 5, 6, 7]])

In [3]:
# a list of regularizers for each column
ry = [ZeroReg(), NonNegConstraint(), ZeroReg(), ZeroReg()]

In [5]:
# generalized PCA and projection
g = glrm(n_components=2, ry=ry) 
g.set_training_data(inputs=A)
g.fit()
a_new = np.array([6, 7, 8, 9]) 
x = g.transform(inputs=a_new) 

In [6]:
x

array([[1.43095194],
       [1.81636534]])

In [7]:
# PCA 
h = glrm(n_components=2, offset=True, scale=True)

In [8]:
h.fit_transform(pd.DataFrame(A))

0    1
0 -0.065039  1.0
1 -0.919171  1.0
2 -1.172617  1.0

In [9]:
h.fit_transform(A)

array([[-1.33756063,  1.        ],
       [-2.97759979,  1.        ],
       [-3.26232626,  1.        ]])

In [10]:
B = np.array([[1, 2, np.nan, 4], [2, 4, np.nan, 8], [4, 5, np.nan, 7]])
h2 = glrm(n_components=3)
h2.fit_transform(B)

array([[-2.16709309e+00, -7.08322964e-01,  8.22714702e-02],
       [-4.32141035e+00, -1.38158896e+00,  1.81437592e-01],
       [-3.71795317e+00,  1.96465852e-03,  2.83572027e+00]])

In [11]:
#Python automatically converts integers to floats, thus I have not implemented the functionality of initializing losses and regularizers by types
a = np.array([[1, 2], [3.2, 4.2]])