In [1]:
import numpy as np
import pandas as pd
from init import *

In [2]:
# a numpy array with missing entry to fit GLRM onto
A = np.array([[1, 2, np.nan, 4], [2, 4, 6, 8], [4, 5, 6, 7]])

In [10]:
# a list of regularizers for each column
ry = [ZeroReg(), NonNegConstraint(), ZeroReg(), ZeroReg()]

In [11]:
# generalized PCA and projection
g = glrm(n_components=2, ry=ry) 
g.set_training_data(inputs=A)
g.fit()
a_new = np.array([6, 7, 8, 9]) 
x = g.produce(inputs=a_new) 

In [13]:
x

array([[ 2.08756711],
       [-4.24421991]])

In [8]:
# PCA 
h = glrm(n_components=2, offset=True, scale=True)

In [9]:
h.fit_transform(pd.DataFrame(A))

array([[0.89127751, 1.98454287, 3.5870526 , 4.18023421],
       [2.85037246, 4.26518677, 5.75035484, 7.09264061],
       [3.28222272, 4.76791722, 6.22721924, 7.73463271]])

In [10]:
h.fit_transform(A)

array([[1.19013792, 1.86129339, 2.91885838, 4.00156825],
       [2.81024151, 4.36575622, 5.77447742, 7.23637535],
       [3.05730606, 4.74768487, 6.20995713, 7.72968094]])

In [17]:
B = np.array([[1, 2, np.nan, 4], [2, 4, np.nan, 8], [4, 5, np.nan, 7]])
h2 = glrm(n_components=3)
h2.fit_transform(B)

array([[0.99985907, 1.99818528, 3.99674977],
       [1.99976466, 4.00242588, 7.99934368],
       [4.00082593, 4.98856182, 6.99988752]])

In [18]:
#Python automatically converts integers to floats, thus I have not implemented the functionality of initializing losses and regularizers by types
a = np.array([[1, 2], [3.2, 4.2]])