In [1]:
import numpy as np
import pandas as pd
from init import *

In [2]:
# a numpy array with missing entry to fit GLRM onto
A = np.array([[1, 2, np.nan, 4], [2, 4, 6, 8], [4, 5, 6, 7]])

In [3]:
# a list of regularizers for each column
ry = [ZeroReg(), NonNegConstraint(), ZeroReg(), ZeroReg()]

In [4]:
# generalized PCA and projection
g = glrm(n_components=2, ry=ry) 
g.set_training_data(inputs=A)
g.fit()
a_new = np.array([6, 7, 8, 9]) 
x = g.transform(inputs=a_new) 

In [5]:
x

array([[ 3.65388666],
       [-0.43974294]])

In [6]:
# PCA 
h = glrm(n_components=2, offset=True, scale=True)

In [7]:
h.fit_impute(pd.DataFrame(A))

0         1         2         3
0  0.854339  1.991302  4.355311  4.264312
1  2.796350  4.190537  5.777283  6.974481
2  3.363850  4.833203  6.192816  7.766454

In [11]:
h.fit_transform(A)

array([[0.41333745, 1.        ],
       [1.16132327, 1.        ],
       [1.3819136 , 1.        ]])

In [9]:
B = np.array([[1, 2, np.nan, 4], [2, 4, np.nan, 8], [4, 5, np.nan, 7]])
h2 = glrm(n_components=3)
h2.fit_transform(B)

array([[-1.06595238, -0.82868562, -0.32365888],
       [-2.12920767, -1.64910571, -0.65757441],
       [-1.81494602, -0.57559055, -2.28062293]])

In [10]:
#Python automatically converts integers to floats, thus I have not implemented the functionality of initializing losses and regularizers by types
a = np.array([[1, 2], [3.2, 4.2]])